### GET request to example server
GET http://localhost:8000
Accept: application/json

### GET request to example server with query parameters
GET http://localhost:8000/hello/Gurpreet
Accept: application/json